version: "3.7"
services:
  db:
    deploy:
      replicas: 1
    container_name: pgvector
    image: pgvector/pgvector:pg16
    shm_size: 1g
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      #POSTGRES_PASSWORD: {PG_PASSWORD}
      POSTGRES_DB: users
      #POSTGRES_USER: {PG_USER}
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: null

# docker compose down --rmi all --volumes
# docker image prune --all
# docker volume prune --all